language: generic

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode8.3
      sudo: required

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://github.com/odaceo/script-ubuntu-swiftenv/raw/master/install.sh)" ; fi

script:
  - swift build --configuration release
  - .build/release/hello Odaceo
